version: "3.9"
services:
    backend:
        build: .
        ports:
            - "3001:3001"
        volumes:
            - .:/app
        depends_on:
            - db
            - redis

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: embassador
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - .dbdata:/var/lib/mysql
        ports:
              - "33066:3306"

    redis:
        image: redis
        ports:
            - "6379:6379"



























